export const ORDER_ERROR = "ORDER_ERROR"
export const ORDER_SUCCESS = "ORDER_SUCCESS"
export const ORDER_OPEN = "ORDER_OPEN"
export const ORDER_CLOSE = "ORDER_CLOSE"

export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS"
export const GET_INGREDIENTS_ERROR = "GET_INGREDIENTS_SUCCESS"
export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST"

export const SET_ORDER_DETAIL_OPEN = "SET_ORDER_DETAIL_OPEN"
export const SET_ORDER_DETAIL_CLOSE = "SET_ORDER_DETAIL_CLOSE"

export const CURRENT_INGREDIENT_OPEN = "CURRENT_INGREDIENT_OPEN"
export const CURRENT_INGREDIENT_CLOSE = "CURRENT_INGREDIENT_CLOSE"

export const BURGER_DROP_INGREDIENT = "BURGER_DROP_INGREDIENT"
export const BURGER_DROP_COMPONENT = "BURGER_DROP_COMPONENT"
export const BURGER_DELETE_COMPONENT = "BURGER_DELETE_COMPONENT"
